my:
  name: wusd
  age: 26
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi, I'm ${my.name}
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8&serverTimezone=UTC
    username: root
    password: wusd123..

  jpa:
    hibernate:
      ddl-auto: update # 第一次建表create 后面用update
    show-sql: true

